# Generated by Django 4.2 on 2023-04-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название техники')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='')),
                ('store_type', models.CharField(choices=[('Холодильник', 'Холодильник'), ('Газовая плита', 'Газовая плита'), ('Стиральная машина', 'Стиральная машина'), ('Пылесос', 'Пылесос'), ('Телевизор', 'Телевизор'), ('Утюг', 'Утюг'), ('Фэн', 'Фэн'), ('Ноутбук', 'Ноутбук')], max_length=100)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rate_stars', models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=100)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('store_choices_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_object', to='online_store.store')),
            ],
        ),
    ]
